### ISSUE TITLE
Make starting-strings like `global` or `eslint` configurable

### ISSUE THREAD

**Issue by DerZyklop** [wisniewski94/eslint-plugin-no-comments#4]
I tried another package but it has this issue: 
https://github.com/cartant/eslint-plugin-etc/issues/48

I can not enable it - it would warn about comments starting with `TODO:`, which it shouldn’t. 

The same issue applies to this `eslint-plugin-no-comments`.
Since `eslint-plugin-no-comments` already ignored comments with specific 'starting strings' like `global` and `eslint`, it would be solved it these strings could be configured. This would also be helpful if people use other linters etc. to ignore comments like e.g. 

`// cSpell:ignore Lorem Ipsum`

A solution could look like this:

```json
{
  "plugins": ["no-comments"],
  "rules": {
    "no-comments/disallowComments": ["error", {
      "ignore": ["eslint", "global", "cSpell", "TODO:", "BUG:", "HOTFIX:"]
     }]
  }
}
```

**Comment by wisniewski94** [comment]
Feature added, please check :)

**Comment by DerZyklop** [comment]
Works like a charm!

**Comment by DerZyklop** [comment]
…and btw. I was able to allow all JSDoc comments with that: 
`"allow": [ "\\*\n", "\\*\\s" ],`

**Comment by wisniewski94** [comment]
@DerZyklop, good point, basically you can add any kind of regex. I will add this information in the future to docs. Thanks for the feedback :)
