### ISSUE TITLE
Avoid deletion of commented code if 'warn'

### ISSUE THREAD

**Issue by juanbrujo** [wisniewski94/eslint-plugin-no-comments#5]
Great plugin, but how to avoid the deletion of commented code, just warn about the them?

Thanks!

**Comment by wisniewski94** [comment]
Hi @juanbrujo, sorry for the late response. I looked into it recently and I can't make eslint to remove the code if it's set to error and keep the code if it's set to warn. It would be helpful if somebody show the plugin that works this way. Here's the StackOverflow question:

https://stackoverflow.com/questions/75605080/custom-eslint-plugin-autofix-if-rule-set-to-error-if-warn-suggest-only
