### ISSUE TITLE
JSDoc Comment Issues

### ISSUE THREAD

**Issue by nazhujan** [wisniewski94/eslint-plugin-no-comments#7]
Currently working on project to throw error for unnecessary comment without correct label, which is easily to identify and helpful for the long run. But then I got 1 issue which is unable to ignore the JSDoc Comment which also become a blocker and i need to disable/warn the rules? any solution for this?

**Comment by wisniewski94** [comment]
Yes, under the hood plugin is doing regex match, so there is nothing to stop you from creating your own regex and adding it into allowlist. Note that `/**` and `*/` delimiters are not part of the tested string.

```
module.exports = {
    "env": {
        "browser": true,
        "es2021": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 12
    },
    "plugins": ["no-comments"],
    "rules": {
        "no-comments/disallowComments": [
          "error",
          {
            "allow": [
              "global",
              "eslint",
              "TODO",
              "FIXME",
              "todo",
              `\\*\\s.*\n\\s\\*\\s+@`
            ]
          }
        ]
    }
};
```

Explanation:

- `\*` matches the literal * character
- `\s` matches any whitespace character (space, tab, etc.)
- `.*` matches any character zero or more times (except for newline)
- `\n` matches a newline character
- `\*\s+` matches the * character followed by one or more whitespace characters
- `@` matches the @ character

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/5289996/223729566-84066844-b1bd-47f3-9cfe-6a173a9d0320.png">

<img width="660" alt="image" src="https://user-images.githubusercontent.com/5289996/223729651-b17ac211-6ff5-4a13-93b4-a81fc9e55f28.png">

Note I am not adding this to the source code as regexp is usually heavy in terms of required computation power. Adding such rules will slow down all workspaces including ones that don't use jsdoc

**Comment by tomerh2001** [comment]
@nazhujan I have a no-comments rule in my custom eslint rules: https://github.com/tomerh2001/eslint-plugin-th-rules

Feel free to check it out
